local L = IGAS:NewLocale("IGAS_UI", "zhTW")
if not L then return end

L["Close Menu"] = "關閉菜單"
L["Action Map"] = "動作條映射"
L["None"] = "(無)"
L["Main Bar"] = "主動作條"
L["Bar 1"] = "動作條1"
L["Bar 2"] = "動作條2"
L["Bar 3"] = "動作條3"
L["Bar 4"] = "動作條4"
L["Bar 5"] = "動作條5"
L["Bar 6"] = "動作條6"
L["Quest Bar"] = "任務物品欄"
L["Pet Bar"] = "寵物動作條"
L["Stance Bar"] = "姿態條"
L["Lock Action"] = "鎖定技能"
L["Scale"] = "縮放"
L["Horizontal Margin"] = "水平間距"
L["Vertical Margin"] = "垂直間距"
L["Auto Hide"] = "自動隱藏"
L["Out of combat"] = "脫離戰鬥時"
L["In petbattle"] = "寵物戰鬥中"
L["In vehicle"] = "載具內"
L["Use mouse down"] = "鼠標按下觸發"
L["Key Binding"] = "按鍵綁定"
L["Free Mode"] = "自由模式"
L["Manual Move&Resize"] = "手動調整位置"
L["Save Settings"] = "保存當前配置"
L["Load Settings"] = "讀取配置"
L["Save Layout"] = "保存佈局方案"
L["Load Layout"] = "讀取佈局方案"
L["Hidden MainMenuBar"] = "隱藏原始界面"
L["Delete Bar"] = "刪除動作條"
L["New Bar"] = "新建動作條"
L["Lock Action Bar"] = "鎖定動作條"
L["New Layout"] = "新佈局方案"
L["New Set"] = "新配置"
L["Reset"] = "重置"
L["Do you want use this bar to take place of the blizzard's main action buttons?"] = "你是否打算使用此動作條替代原始動作條?"
L["Please input the new layout name"] = "請輸入新佈局方案名稱"
L["Do you want overwrite the existed layout?"] = "是否確定覆蓋已有的佈局方案?"
L["Do you want reset the layout?"] = "是否確定重置當前佈局?"
L["Do you want load the layout?"] = "是否確定載入指定佈局方案?"
L["Please confirm to delete this action bar"] = "請確認是否刪除該動作條?"
L["Please confirm to create new action bar"] = "請確認是否新建動作條?"
L["Swap Pop-up action"] = "切替彈出條動作"
L["Please input the new set name"] = "請輸入新的配置名稱"
L["Do you want overwrite the existed set?"] = "是否確定覆蓋已有的配置?"
L["Do you want load the set?"] = "是否確定載入該配置?"

L["Spell Binding"] = "技能綁定"
L["Lock Raid Panel"] = "鎖定團隊面板"

L["%s is added to buff line."] = "%s 被加入增益監視列表。"
L["%s is added to spell cooldown line."] = "%s 被加入技能冷卻監視列表。"
L["%s is removed from spell cooldown line."] = "%s 被移出技能冷卻監視列表。"
L["%s is added to item cooldown line."] = "%s 被加入物品冷卻監視列表。"
L["%s is removed from item cooldown line."] = "%s 被移出物品冷卻監視列表。"

L["Lock Unit Frame"] = "鎖定人物面板"

L["Buff panel"] = "增益面板"
L["Disconnect indicator"] = "斷線指示"
L["Debuff panel"] = "減益面板"
L["Group Role indicator"] = "小隊角色指示"
L["My heal prediction"] = "玩家的提前治療量"
L["All heal prediction"] = "全部的提前治療量"
L["Total Absorb"] = "總吸收量"
L["Leader indicator"] = "隊長指示"
L["Target indicator"] = "玩家目標指示"
L["Resurrect indicator"] = "復活指示"
L["ReadyCheck indicator"] = "團隊檢查指示"
L["Raid/Group target indicator"] = "團隊/小隊目標指示"
L["Raid roster indicator"] = "團隊角色指示"
L["Power bar"] = "能力資源條"
L["Name indicator"] = "姓名指示"
L["Range indicator"] = "距離指示"

L["Raid panel"] = "團對面板"
L["Pet panel"] = "寵物面板"

L["Activated"] = "啟用"
L["Deactivate in raid"] = "團隊中禁用"

L["Show"] = "顯示面板"
L["Show in a raid"] = "在團隊中"
L["Show in a party"] = "在小隊中"
L["Show the player in party"] = "在小隊中顯示玩家"
L["Show when solo"] = "在單獨遊戲時"

L["Group By"] = "分組"
L["NONE"] = "無"
L["GROUP"] = "小組"
L["CLASS"] = "職業"
L["ROLE"] = "職責"

L["Sort By"] = "排序"
L["INDEX"] = "順序"
L["NAME"] = "名字"