local L = IGAS:NewLocale("IGAS_UI", "zhCN")
if not L then return end

L["Close Menu"] = "关闭菜单"
L["Action Map"] = "动作条映射"
L["None"] = "(无)"
L["Main Bar"] = "主动作条"
L["Bar 1"] = "动作条1"
L["Bar 2"] = "动作条2"
L["Bar 3"] = "动作条3"
L["Bar 4"] = "动作条4"
L["Bar 5"] = "动作条5"
L["Bar 6"] = "动作条6"
L["Quest Bar"] = "任务物品栏"
L["Pet Bar"] = "宠物动作条"
L["Stance Bar"] = "姿态条"
L["Lock Action"] = "锁定技能"
L["Scale"] = "缩放"
L["Horizontal Margin"] = "水平间距"
L["Vertical Margin"] = "垂直间距"
L["Auto Hide"] = "自动隐藏"
L["Out of combat"] = "脱离战斗时"
L["In petbattle"] = "宠物战斗中"
L["In vehicle"] = "载具内"
L["Use mouse down"] = "鼠标按下触发"
L["Key Binding"] = "按键绑定"
L["Free Mode"] = "自由模式"
L["Manual Move&Resize"] = "手动调整位置"
L["Save Settings"] = "保存当前配置"
L["Load Settings"] = "读取配置"
L["Save Layout"] = "保存布局方案"
L["Load Layout"] = "读取布局方案"
L["Hidden MainMenuBar"] = "隐藏原始界面"
L["Delete Bar"] = "删除动作条"
L["New Bar"] = "新建动作条"
L["Lock Action Bar"] = "锁定动作条"
L["New Layout"] = "新布局方案"
L["New Set"] = "新配置"
L["Reset"] = "重置"
L["Do you want use this bar to take place of the blizzard's main action buttons?"] = "你是否打算使用此动作条替代原始主动作条?"
L["Please input the new layout name"] = "请输入新布局方案名称"
L["Do you want overwrite the existed layout?"] = "是否确定覆盖已有的布局方案?"
L["Do you want reset the layout?"] = "是否确定重置当前布局?"
L["Do you want load the layout?"] = "是否确定载入指定布局方案?"
L["Please confirm to delete this action bar"] = "请确认是否删除这个动作条?"
L["Please confirm to create new action bar"] = "请确认是否新建动作条?"
L["Swap Pop-up action"] = "切换弹出条动作"
L["Please input the new set name"] = "请输入新的配置名称"
L["Do you want overwrite the existed set?"] = "是否覆盖已有的配置?"
L["Do you want load the set?"] = "是否确定载入该配置?"

L["Spell Binding"] = "技能绑定"
L["Lock Raid Panel"] = "锁定团队面板"

L["%s is added to buff line."] = "%s 被加入增益监视列表。"
L["%s is added to spell cooldown line."] = "%s 被加入技能冷却监视列表。"
L["%s is removed from spell cooldown line."] = "%s 被移出技能冷却监视列表"
L["%s is added to item cooldown line."] = "%s 被加入物品冷却监视列表。"
L["%s is removed from item cooldown line."] = "%s 被移出物品冷却监视列表。"

L["Lock Unit Frame"] = "锁定人物面板"

L["Buff panel"] = "增益面板"
L["Disconnect indicator"] = "断线指示"
L["Debuff panel"] = "减益面板"
L["Group Role indicator"] = "小队角色指示"
L["My heal prediction"] = "玩家的提前治疗量"
L["All heal prediction"] = "全部的提前治疗量"
L["Total Absorb"] = "总吸收量"
L["Leader indicator"] = "队长指示"
L["Target indicator"] = "玩家目标指示"
L["Resurrect indicator"] = "复活指示"
L["ReadyCheck indicator"] = "团队检查指示"
L["Raid/Group target indicator"] = "团队/小队目标指示"
L["Raid roster indicator"] = "团队角色指示"
L["Power bar"] = "能力资源条"
L["Name indicator"] = "姓名指示"
L["Range indicator"] = "距离指示"

L["Show"] = "显示面板"
L["Show in a raid"] = "在团队中"
L["Show in a party"] = "在小队中"
L["Show the player in party"] = "在小队中显示玩家"
L["Show when solo"] = "在单独游戏时"

L["Group By"] = "分组"
L["NONE"] = "无"
L["GROUP"] = "小组"
L["CLASS"] = "职业"
L["ROLE"] = "职责"

L["Sort By"] = "排序"
L["INDEX"] = "顺序"
L["NAME"] = "名字"